#!/bin/sh

APPDIR=$(dirname "$0")
$APPDIR/java/bin/java -Djna.nosys=true -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR:$APPDIR/lib/ArmLink.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/G4P.jar:$APPDIR/lib/serial.jar:$APPDIR/lib/jssc.jar:$APPDIR/lib/gstreamer-java.jar:$APPDIR/lib/video.jar:$APPDIR/lib/jna.jar" ArmLink "$@"
